/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.baidu.palo.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TErrorHubType implements org.apache.thrift.TEnum {
  MYSQL(0),
  NULL_TYPE(1);

  private final int value;

  private TErrorHubType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TErrorHubType findByValue(int value) { 
    switch (value) {
      case 0:
        return MYSQL;
      case 1:
        return NULL_TYPE;
      default:
        return null;
    }
  }
}
