/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.baidu.palo.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2018-05-01")
public class TPaloScanRange implements org.apache.thrift.TBase<TPaloScanRange, TPaloScanRange._Fields>, java.io.Serializable, Cloneable, Comparable<TPaloScanRange> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TPaloScanRange");

  private static final org.apache.thrift.protocol.TField HOSTS_FIELD_DESC = new org.apache.thrift.protocol.TField("hosts", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField SCHEMA_HASH_FIELD_DESC = new org.apache.thrift.protocol.TField("schema_hash", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField VERSION_FIELD_DESC = new org.apache.thrift.protocol.TField("version", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField VERSION_HASH_FIELD_DESC = new org.apache.thrift.protocol.TField("version_hash", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField TABLET_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("tablet_id", org.apache.thrift.protocol.TType.I64, (short)5);
  private static final org.apache.thrift.protocol.TField DB_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("db_name", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField PARTITION_COLUMN_RANGES_FIELD_DESC = new org.apache.thrift.protocol.TField("partition_column_ranges", org.apache.thrift.protocol.TType.LIST, (short)7);
  private static final org.apache.thrift.protocol.TField INDEX_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("index_name", org.apache.thrift.protocol.TType.STRING, (short)8);
  private static final org.apache.thrift.protocol.TField TABLE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("table_name", org.apache.thrift.protocol.TType.STRING, (short)9);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TPaloScanRangeStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TPaloScanRangeTupleSchemeFactory());
  }

  public List<com.baidu.palo.thrift.TNetworkAddress> hosts; // required
  public String schema_hash; // required
  public String version; // required
  public String version_hash; // required
  public long tablet_id; // required
  public String db_name; // required
  public List<TKeyRange> partition_column_ranges; // optional
  public String index_name; // optional
  public String table_name; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    HOSTS((short)1, "hosts"),
    SCHEMA_HASH((short)2, "schema_hash"),
    VERSION((short)3, "version"),
    VERSION_HASH((short)4, "version_hash"),
    TABLET_ID((short)5, "tablet_id"),
    DB_NAME((short)6, "db_name"),
    PARTITION_COLUMN_RANGES((short)7, "partition_column_ranges"),
    INDEX_NAME((short)8, "index_name"),
    TABLE_NAME((short)9, "table_name");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // HOSTS
          return HOSTS;
        case 2: // SCHEMA_HASH
          return SCHEMA_HASH;
        case 3: // VERSION
          return VERSION;
        case 4: // VERSION_HASH
          return VERSION_HASH;
        case 5: // TABLET_ID
          return TABLET_ID;
        case 6: // DB_NAME
          return DB_NAME;
        case 7: // PARTITION_COLUMN_RANGES
          return PARTITION_COLUMN_RANGES;
        case 8: // INDEX_NAME
          return INDEX_NAME;
        case 9: // TABLE_NAME
          return TABLE_NAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TABLET_ID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.PARTITION_COLUMN_RANGES,_Fields.INDEX_NAME,_Fields.TABLE_NAME};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.HOSTS, new org.apache.thrift.meta_data.FieldMetaData("hosts", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.baidu.palo.thrift.TNetworkAddress.class))));
    tmpMap.put(_Fields.SCHEMA_HASH, new org.apache.thrift.meta_data.FieldMetaData("schema_hash", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VERSION, new org.apache.thrift.meta_data.FieldMetaData("version", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VERSION_HASH, new org.apache.thrift.meta_data.FieldMetaData("version_hash", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TABLET_ID, new org.apache.thrift.meta_data.FieldMetaData("tablet_id", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "TTabletId")));
    tmpMap.put(_Fields.DB_NAME, new org.apache.thrift.meta_data.FieldMetaData("db_name", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PARTITION_COLUMN_RANGES, new org.apache.thrift.meta_data.FieldMetaData("partition_column_ranges", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TKeyRange.class))));
    tmpMap.put(_Fields.INDEX_NAME, new org.apache.thrift.meta_data.FieldMetaData("index_name", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TABLE_NAME, new org.apache.thrift.meta_data.FieldMetaData("table_name", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TPaloScanRange.class, metaDataMap);
  }

  public TPaloScanRange() {
  }

  public TPaloScanRange(
    List<com.baidu.palo.thrift.TNetworkAddress> hosts,
    String schema_hash,
    String version,
    String version_hash,
    long tablet_id,
    String db_name)
  {
    this();
    this.hosts = hosts;
    this.schema_hash = schema_hash;
    this.version = version;
    this.version_hash = version_hash;
    this.tablet_id = tablet_id;
    setTablet_idIsSet(true);
    this.db_name = db_name;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TPaloScanRange(TPaloScanRange other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetHosts()) {
      List<com.baidu.palo.thrift.TNetworkAddress> __this__hosts = new ArrayList<com.baidu.palo.thrift.TNetworkAddress>(other.hosts.size());
      for (com.baidu.palo.thrift.TNetworkAddress other_element : other.hosts) {
        __this__hosts.add(new com.baidu.palo.thrift.TNetworkAddress(other_element));
      }
      this.hosts = __this__hosts;
    }
    if (other.isSetSchema_hash()) {
      this.schema_hash = other.schema_hash;
    }
    if (other.isSetVersion()) {
      this.version = other.version;
    }
    if (other.isSetVersion_hash()) {
      this.version_hash = other.version_hash;
    }
    this.tablet_id = other.tablet_id;
    if (other.isSetDb_name()) {
      this.db_name = other.db_name;
    }
    if (other.isSetPartition_column_ranges()) {
      List<TKeyRange> __this__partition_column_ranges = new ArrayList<TKeyRange>(other.partition_column_ranges.size());
      for (TKeyRange other_element : other.partition_column_ranges) {
        __this__partition_column_ranges.add(new TKeyRange(other_element));
      }
      this.partition_column_ranges = __this__partition_column_ranges;
    }
    if (other.isSetIndex_name()) {
      this.index_name = other.index_name;
    }
    if (other.isSetTable_name()) {
      this.table_name = other.table_name;
    }
  }

  public TPaloScanRange deepCopy() {
    return new TPaloScanRange(this);
  }

  @Override
  public void clear() {
    this.hosts = null;
    this.schema_hash = null;
    this.version = null;
    this.version_hash = null;
    setTablet_idIsSet(false);
    this.tablet_id = 0;
    this.db_name = null;
    this.partition_column_ranges = null;
    this.index_name = null;
    this.table_name = null;
  }

  public int getHostsSize() {
    return (this.hosts == null) ? 0 : this.hosts.size();
  }

  public java.util.Iterator<com.baidu.palo.thrift.TNetworkAddress> getHostsIterator() {
    return (this.hosts == null) ? null : this.hosts.iterator();
  }

  public void addToHosts(com.baidu.palo.thrift.TNetworkAddress elem) {
    if (this.hosts == null) {
      this.hosts = new ArrayList<com.baidu.palo.thrift.TNetworkAddress>();
    }
    this.hosts.add(elem);
  }

  public List<com.baidu.palo.thrift.TNetworkAddress> getHosts() {
    return this.hosts;
  }

  public TPaloScanRange setHosts(List<com.baidu.palo.thrift.TNetworkAddress> hosts) {
    this.hosts = hosts;
    return this;
  }

  public void unsetHosts() {
    this.hosts = null;
  }

  /** Returns true if field hosts is set (has been assigned a value) and false otherwise */
  public boolean isSetHosts() {
    return this.hosts != null;
  }

  public void setHostsIsSet(boolean value) {
    if (!value) {
      this.hosts = null;
    }
  }

  public String getSchema_hash() {
    return this.schema_hash;
  }

  public TPaloScanRange setSchema_hash(String schema_hash) {
    this.schema_hash = schema_hash;
    return this;
  }

  public void unsetSchema_hash() {
    this.schema_hash = null;
  }

  /** Returns true if field schema_hash is set (has been assigned a value) and false otherwise */
  public boolean isSetSchema_hash() {
    return this.schema_hash != null;
  }

  public void setSchema_hashIsSet(boolean value) {
    if (!value) {
      this.schema_hash = null;
    }
  }

  public String getVersion() {
    return this.version;
  }

  public TPaloScanRange setVersion(String version) {
    this.version = version;
    return this;
  }

  public void unsetVersion() {
    this.version = null;
  }

  /** Returns true if field version is set (has been assigned a value) and false otherwise */
  public boolean isSetVersion() {
    return this.version != null;
  }

  public void setVersionIsSet(boolean value) {
    if (!value) {
      this.version = null;
    }
  }

  public String getVersion_hash() {
    return this.version_hash;
  }

  public TPaloScanRange setVersion_hash(String version_hash) {
    this.version_hash = version_hash;
    return this;
  }

  public void unsetVersion_hash() {
    this.version_hash = null;
  }

  /** Returns true if field version_hash is set (has been assigned a value) and false otherwise */
  public boolean isSetVersion_hash() {
    return this.version_hash != null;
  }

  public void setVersion_hashIsSet(boolean value) {
    if (!value) {
      this.version_hash = null;
    }
  }

  public long getTablet_id() {
    return this.tablet_id;
  }

  public TPaloScanRange setTablet_id(long tablet_id) {
    this.tablet_id = tablet_id;
    setTablet_idIsSet(true);
    return this;
  }

  public void unsetTablet_id() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TABLET_ID_ISSET_ID);
  }

  /** Returns true if field tablet_id is set (has been assigned a value) and false otherwise */
  public boolean isSetTablet_id() {
    return EncodingUtils.testBit(__isset_bitfield, __TABLET_ID_ISSET_ID);
  }

  public void setTablet_idIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TABLET_ID_ISSET_ID, value);
  }

  public String getDb_name() {
    return this.db_name;
  }

  public TPaloScanRange setDb_name(String db_name) {
    this.db_name = db_name;
    return this;
  }

  public void unsetDb_name() {
    this.db_name = null;
  }

  /** Returns true if field db_name is set (has been assigned a value) and false otherwise */
  public boolean isSetDb_name() {
    return this.db_name != null;
  }

  public void setDb_nameIsSet(boolean value) {
    if (!value) {
      this.db_name = null;
    }
  }

  public int getPartition_column_rangesSize() {
    return (this.partition_column_ranges == null) ? 0 : this.partition_column_ranges.size();
  }

  public java.util.Iterator<TKeyRange> getPartition_column_rangesIterator() {
    return (this.partition_column_ranges == null) ? null : this.partition_column_ranges.iterator();
  }

  public void addToPartition_column_ranges(TKeyRange elem) {
    if (this.partition_column_ranges == null) {
      this.partition_column_ranges = new ArrayList<TKeyRange>();
    }
    this.partition_column_ranges.add(elem);
  }

  public List<TKeyRange> getPartition_column_ranges() {
    return this.partition_column_ranges;
  }

  public TPaloScanRange setPartition_column_ranges(List<TKeyRange> partition_column_ranges) {
    this.partition_column_ranges = partition_column_ranges;
    return this;
  }

  public void unsetPartition_column_ranges() {
    this.partition_column_ranges = null;
  }

  /** Returns true if field partition_column_ranges is set (has been assigned a value) and false otherwise */
  public boolean isSetPartition_column_ranges() {
    return this.partition_column_ranges != null;
  }

  public void setPartition_column_rangesIsSet(boolean value) {
    if (!value) {
      this.partition_column_ranges = null;
    }
  }

  public String getIndex_name() {
    return this.index_name;
  }

  public TPaloScanRange setIndex_name(String index_name) {
    this.index_name = index_name;
    return this;
  }

  public void unsetIndex_name() {
    this.index_name = null;
  }

  /** Returns true if field index_name is set (has been assigned a value) and false otherwise */
  public boolean isSetIndex_name() {
    return this.index_name != null;
  }

  public void setIndex_nameIsSet(boolean value) {
    if (!value) {
      this.index_name = null;
    }
  }

  public String getTable_name() {
    return this.table_name;
  }

  public TPaloScanRange setTable_name(String table_name) {
    this.table_name = table_name;
    return this;
  }

  public void unsetTable_name() {
    this.table_name = null;
  }

  /** Returns true if field table_name is set (has been assigned a value) and false otherwise */
  public boolean isSetTable_name() {
    return this.table_name != null;
  }

  public void setTable_nameIsSet(boolean value) {
    if (!value) {
      this.table_name = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case HOSTS:
      if (value == null) {
        unsetHosts();
      } else {
        setHosts((List<com.baidu.palo.thrift.TNetworkAddress>)value);
      }
      break;

    case SCHEMA_HASH:
      if (value == null) {
        unsetSchema_hash();
      } else {
        setSchema_hash((String)value);
      }
      break;

    case VERSION:
      if (value == null) {
        unsetVersion();
      } else {
        setVersion((String)value);
      }
      break;

    case VERSION_HASH:
      if (value == null) {
        unsetVersion_hash();
      } else {
        setVersion_hash((String)value);
      }
      break;

    case TABLET_ID:
      if (value == null) {
        unsetTablet_id();
      } else {
        setTablet_id((Long)value);
      }
      break;

    case DB_NAME:
      if (value == null) {
        unsetDb_name();
      } else {
        setDb_name((String)value);
      }
      break;

    case PARTITION_COLUMN_RANGES:
      if (value == null) {
        unsetPartition_column_ranges();
      } else {
        setPartition_column_ranges((List<TKeyRange>)value);
      }
      break;

    case INDEX_NAME:
      if (value == null) {
        unsetIndex_name();
      } else {
        setIndex_name((String)value);
      }
      break;

    case TABLE_NAME:
      if (value == null) {
        unsetTable_name();
      } else {
        setTable_name((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case HOSTS:
      return getHosts();

    case SCHEMA_HASH:
      return getSchema_hash();

    case VERSION:
      return getVersion();

    case VERSION_HASH:
      return getVersion_hash();

    case TABLET_ID:
      return getTablet_id();

    case DB_NAME:
      return getDb_name();

    case PARTITION_COLUMN_RANGES:
      return getPartition_column_ranges();

    case INDEX_NAME:
      return getIndex_name();

    case TABLE_NAME:
      return getTable_name();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case HOSTS:
      return isSetHosts();
    case SCHEMA_HASH:
      return isSetSchema_hash();
    case VERSION:
      return isSetVersion();
    case VERSION_HASH:
      return isSetVersion_hash();
    case TABLET_ID:
      return isSetTablet_id();
    case DB_NAME:
      return isSetDb_name();
    case PARTITION_COLUMN_RANGES:
      return isSetPartition_column_ranges();
    case INDEX_NAME:
      return isSetIndex_name();
    case TABLE_NAME:
      return isSetTable_name();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TPaloScanRange)
      return this.equals((TPaloScanRange)that);
    return false;
  }

  public boolean equals(TPaloScanRange that) {
    if (that == null)
      return false;

    boolean this_present_hosts = true && this.isSetHosts();
    boolean that_present_hosts = true && that.isSetHosts();
    if (this_present_hosts || that_present_hosts) {
      if (!(this_present_hosts && that_present_hosts))
        return false;
      if (!this.hosts.equals(that.hosts))
        return false;
    }

    boolean this_present_schema_hash = true && this.isSetSchema_hash();
    boolean that_present_schema_hash = true && that.isSetSchema_hash();
    if (this_present_schema_hash || that_present_schema_hash) {
      if (!(this_present_schema_hash && that_present_schema_hash))
        return false;
      if (!this.schema_hash.equals(that.schema_hash))
        return false;
    }

    boolean this_present_version = true && this.isSetVersion();
    boolean that_present_version = true && that.isSetVersion();
    if (this_present_version || that_present_version) {
      if (!(this_present_version && that_present_version))
        return false;
      if (!this.version.equals(that.version))
        return false;
    }

    boolean this_present_version_hash = true && this.isSetVersion_hash();
    boolean that_present_version_hash = true && that.isSetVersion_hash();
    if (this_present_version_hash || that_present_version_hash) {
      if (!(this_present_version_hash && that_present_version_hash))
        return false;
      if (!this.version_hash.equals(that.version_hash))
        return false;
    }

    boolean this_present_tablet_id = true;
    boolean that_present_tablet_id = true;
    if (this_present_tablet_id || that_present_tablet_id) {
      if (!(this_present_tablet_id && that_present_tablet_id))
        return false;
      if (this.tablet_id != that.tablet_id)
        return false;
    }

    boolean this_present_db_name = true && this.isSetDb_name();
    boolean that_present_db_name = true && that.isSetDb_name();
    if (this_present_db_name || that_present_db_name) {
      if (!(this_present_db_name && that_present_db_name))
        return false;
      if (!this.db_name.equals(that.db_name))
        return false;
    }

    boolean this_present_partition_column_ranges = true && this.isSetPartition_column_ranges();
    boolean that_present_partition_column_ranges = true && that.isSetPartition_column_ranges();
    if (this_present_partition_column_ranges || that_present_partition_column_ranges) {
      if (!(this_present_partition_column_ranges && that_present_partition_column_ranges))
        return false;
      if (!this.partition_column_ranges.equals(that.partition_column_ranges))
        return false;
    }

    boolean this_present_index_name = true && this.isSetIndex_name();
    boolean that_present_index_name = true && that.isSetIndex_name();
    if (this_present_index_name || that_present_index_name) {
      if (!(this_present_index_name && that_present_index_name))
        return false;
      if (!this.index_name.equals(that.index_name))
        return false;
    }

    boolean this_present_table_name = true && this.isSetTable_name();
    boolean that_present_table_name = true && that.isSetTable_name();
    if (this_present_table_name || that_present_table_name) {
      if (!(this_present_table_name && that_present_table_name))
        return false;
      if (!this.table_name.equals(that.table_name))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_hosts = true && (isSetHosts());
    list.add(present_hosts);
    if (present_hosts)
      list.add(hosts);

    boolean present_schema_hash = true && (isSetSchema_hash());
    list.add(present_schema_hash);
    if (present_schema_hash)
      list.add(schema_hash);

    boolean present_version = true && (isSetVersion());
    list.add(present_version);
    if (present_version)
      list.add(version);

    boolean present_version_hash = true && (isSetVersion_hash());
    list.add(present_version_hash);
    if (present_version_hash)
      list.add(version_hash);

    boolean present_tablet_id = true;
    list.add(present_tablet_id);
    if (present_tablet_id)
      list.add(tablet_id);

    boolean present_db_name = true && (isSetDb_name());
    list.add(present_db_name);
    if (present_db_name)
      list.add(db_name);

    boolean present_partition_column_ranges = true && (isSetPartition_column_ranges());
    list.add(present_partition_column_ranges);
    if (present_partition_column_ranges)
      list.add(partition_column_ranges);

    boolean present_index_name = true && (isSetIndex_name());
    list.add(present_index_name);
    if (present_index_name)
      list.add(index_name);

    boolean present_table_name = true && (isSetTable_name());
    list.add(present_table_name);
    if (present_table_name)
      list.add(table_name);

    return list.hashCode();
  }

  @Override
  public int compareTo(TPaloScanRange other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetHosts()).compareTo(other.isSetHosts());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHosts()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hosts, other.hosts);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSchema_hash()).compareTo(other.isSetSchema_hash());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSchema_hash()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.schema_hash, other.schema_hash);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetVersion()).compareTo(other.isSetVersion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVersion()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.version, other.version);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetVersion_hash()).compareTo(other.isSetVersion_hash());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVersion_hash()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.version_hash, other.version_hash);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTablet_id()).compareTo(other.isSetTablet_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTablet_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tablet_id, other.tablet_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDb_name()).compareTo(other.isSetDb_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDb_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.db_name, other.db_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPartition_column_ranges()).compareTo(other.isSetPartition_column_ranges());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPartition_column_ranges()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.partition_column_ranges, other.partition_column_ranges);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIndex_name()).compareTo(other.isSetIndex_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIndex_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.index_name, other.index_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTable_name()).compareTo(other.isSetTable_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTable_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.table_name, other.table_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TPaloScanRange(");
    boolean first = true;

    sb.append("hosts:");
    if (this.hosts == null) {
      sb.append("null");
    } else {
      sb.append(this.hosts);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("schema_hash:");
    if (this.schema_hash == null) {
      sb.append("null");
    } else {
      sb.append(this.schema_hash);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("version:");
    if (this.version == null) {
      sb.append("null");
    } else {
      sb.append(this.version);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("version_hash:");
    if (this.version_hash == null) {
      sb.append("null");
    } else {
      sb.append(this.version_hash);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("tablet_id:");
    sb.append(this.tablet_id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("db_name:");
    if (this.db_name == null) {
      sb.append("null");
    } else {
      sb.append(this.db_name);
    }
    first = false;
    if (isSetPartition_column_ranges()) {
      if (!first) sb.append(", ");
      sb.append("partition_column_ranges:");
      if (this.partition_column_ranges == null) {
        sb.append("null");
      } else {
        sb.append(this.partition_column_ranges);
      }
      first = false;
    }
    if (isSetIndex_name()) {
      if (!first) sb.append(", ");
      sb.append("index_name:");
      if (this.index_name == null) {
        sb.append("null");
      } else {
        sb.append(this.index_name);
      }
      first = false;
    }
    if (isSetTable_name()) {
      if (!first) sb.append(", ");
      sb.append("table_name:");
      if (this.table_name == null) {
        sb.append("null");
      } else {
        sb.append(this.table_name);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (hosts == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'hosts' was not present! Struct: " + toString());
    }
    if (schema_hash == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'schema_hash' was not present! Struct: " + toString());
    }
    if (version == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'version' was not present! Struct: " + toString());
    }
    if (version_hash == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'version_hash' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'tablet_id' because it's a primitive and you chose the non-beans generator.
    if (db_name == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'db_name' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TPaloScanRangeStandardSchemeFactory implements SchemeFactory {
    public TPaloScanRangeStandardScheme getScheme() {
      return new TPaloScanRangeStandardScheme();
    }
  }

  private static class TPaloScanRangeStandardScheme extends StandardScheme<TPaloScanRange> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TPaloScanRange struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // HOSTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.hosts = new ArrayList<com.baidu.palo.thrift.TNetworkAddress>(_list0.size);
                com.baidu.palo.thrift.TNetworkAddress _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new com.baidu.palo.thrift.TNetworkAddress();
                  _elem1.read(iprot);
                  struct.hosts.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setHostsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SCHEMA_HASH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.schema_hash = iprot.readString();
              struct.setSchema_hashIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // VERSION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.version = iprot.readString();
              struct.setVersionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // VERSION_HASH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.version_hash = iprot.readString();
              struct.setVersion_hashIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // TABLET_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.tablet_id = iprot.readI64();
              struct.setTablet_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // DB_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.db_name = iprot.readString();
              struct.setDb_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // PARTITION_COLUMN_RANGES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list3 = iprot.readListBegin();
                struct.partition_column_ranges = new ArrayList<TKeyRange>(_list3.size);
                TKeyRange _elem4;
                for (int _i5 = 0; _i5 < _list3.size; ++_i5)
                {
                  _elem4 = new TKeyRange();
                  _elem4.read(iprot);
                  struct.partition_column_ranges.add(_elem4);
                }
                iprot.readListEnd();
              }
              struct.setPartition_column_rangesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // INDEX_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.index_name = iprot.readString();
              struct.setIndex_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // TABLE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.table_name = iprot.readString();
              struct.setTable_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetTablet_id()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'tablet_id' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TPaloScanRange struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.hosts != null) {
        oprot.writeFieldBegin(HOSTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.hosts.size()));
          for (com.baidu.palo.thrift.TNetworkAddress _iter6 : struct.hosts)
          {
            _iter6.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.schema_hash != null) {
        oprot.writeFieldBegin(SCHEMA_HASH_FIELD_DESC);
        oprot.writeString(struct.schema_hash);
        oprot.writeFieldEnd();
      }
      if (struct.version != null) {
        oprot.writeFieldBegin(VERSION_FIELD_DESC);
        oprot.writeString(struct.version);
        oprot.writeFieldEnd();
      }
      if (struct.version_hash != null) {
        oprot.writeFieldBegin(VERSION_HASH_FIELD_DESC);
        oprot.writeString(struct.version_hash);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TABLET_ID_FIELD_DESC);
      oprot.writeI64(struct.tablet_id);
      oprot.writeFieldEnd();
      if (struct.db_name != null) {
        oprot.writeFieldBegin(DB_NAME_FIELD_DESC);
        oprot.writeString(struct.db_name);
        oprot.writeFieldEnd();
      }
      if (struct.partition_column_ranges != null) {
        if (struct.isSetPartition_column_ranges()) {
          oprot.writeFieldBegin(PARTITION_COLUMN_RANGES_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.partition_column_ranges.size()));
            for (TKeyRange _iter7 : struct.partition_column_ranges)
            {
              _iter7.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.index_name != null) {
        if (struct.isSetIndex_name()) {
          oprot.writeFieldBegin(INDEX_NAME_FIELD_DESC);
          oprot.writeString(struct.index_name);
          oprot.writeFieldEnd();
        }
      }
      if (struct.table_name != null) {
        if (struct.isSetTable_name()) {
          oprot.writeFieldBegin(TABLE_NAME_FIELD_DESC);
          oprot.writeString(struct.table_name);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TPaloScanRangeTupleSchemeFactory implements SchemeFactory {
    public TPaloScanRangeTupleScheme getScheme() {
      return new TPaloScanRangeTupleScheme();
    }
  }

  private static class TPaloScanRangeTupleScheme extends TupleScheme<TPaloScanRange> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TPaloScanRange struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.hosts.size());
        for (com.baidu.palo.thrift.TNetworkAddress _iter8 : struct.hosts)
        {
          _iter8.write(oprot);
        }
      }
      oprot.writeString(struct.schema_hash);
      oprot.writeString(struct.version);
      oprot.writeString(struct.version_hash);
      oprot.writeI64(struct.tablet_id);
      oprot.writeString(struct.db_name);
      BitSet optionals = new BitSet();
      if (struct.isSetPartition_column_ranges()) {
        optionals.set(0);
      }
      if (struct.isSetIndex_name()) {
        optionals.set(1);
      }
      if (struct.isSetTable_name()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetPartition_column_ranges()) {
        {
          oprot.writeI32(struct.partition_column_ranges.size());
          for (TKeyRange _iter9 : struct.partition_column_ranges)
          {
            _iter9.write(oprot);
          }
        }
      }
      if (struct.isSetIndex_name()) {
        oprot.writeString(struct.index_name);
      }
      if (struct.isSetTable_name()) {
        oprot.writeString(struct.table_name);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TPaloScanRange struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TList _list10 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.hosts = new ArrayList<com.baidu.palo.thrift.TNetworkAddress>(_list10.size);
        com.baidu.palo.thrift.TNetworkAddress _elem11;
        for (int _i12 = 0; _i12 < _list10.size; ++_i12)
        {
          _elem11 = new com.baidu.palo.thrift.TNetworkAddress();
          _elem11.read(iprot);
          struct.hosts.add(_elem11);
        }
      }
      struct.setHostsIsSet(true);
      struct.schema_hash = iprot.readString();
      struct.setSchema_hashIsSet(true);
      struct.version = iprot.readString();
      struct.setVersionIsSet(true);
      struct.version_hash = iprot.readString();
      struct.setVersion_hashIsSet(true);
      struct.tablet_id = iprot.readI64();
      struct.setTablet_idIsSet(true);
      struct.db_name = iprot.readString();
      struct.setDb_nameIsSet(true);
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.partition_column_ranges = new ArrayList<TKeyRange>(_list13.size);
          TKeyRange _elem14;
          for (int _i15 = 0; _i15 < _list13.size; ++_i15)
          {
            _elem14 = new TKeyRange();
            _elem14.read(iprot);
            struct.partition_column_ranges.add(_elem14);
          }
        }
        struct.setPartition_column_rangesIsSet(true);
      }
      if (incoming.get(1)) {
        struct.index_name = iprot.readString();
        struct.setIndex_nameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.table_name = iprot.readString();
        struct.setTable_nameIsSet(true);
      }
    }
  }

}

