/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.baidu.palo.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2018-05-01")
public class TRangeValue implements org.apache.thrift.TBase<TRangeValue, TRangeValue._Fields>, java.io.Serializable, Cloneable, Comparable<TRangeValue> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TRangeValue");

  private static final org.apache.thrift.protocol.TField VALUE_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("value_list", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TRangeValueStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TRangeValueTupleSchemeFactory());
  }

  public List<TValue> value_list; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VALUE_LIST((short)1, "value_list");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VALUE_LIST
          return VALUE_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VALUE_LIST, new org.apache.thrift.meta_data.FieldMetaData("value_list", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TValue.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TRangeValue.class, metaDataMap);
  }

  public TRangeValue() {
  }

  public TRangeValue(
    List<TValue> value_list)
  {
    this();
    this.value_list = value_list;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TRangeValue(TRangeValue other) {
    if (other.isSetValue_list()) {
      List<TValue> __this__value_list = new ArrayList<TValue>(other.value_list.size());
      for (TValue other_element : other.value_list) {
        __this__value_list.add(new TValue(other_element));
      }
      this.value_list = __this__value_list;
    }
  }

  public TRangeValue deepCopy() {
    return new TRangeValue(this);
  }

  @Override
  public void clear() {
    this.value_list = null;
  }

  public int getValue_listSize() {
    return (this.value_list == null) ? 0 : this.value_list.size();
  }

  public java.util.Iterator<TValue> getValue_listIterator() {
    return (this.value_list == null) ? null : this.value_list.iterator();
  }

  public void addToValue_list(TValue elem) {
    if (this.value_list == null) {
      this.value_list = new ArrayList<TValue>();
    }
    this.value_list.add(elem);
  }

  public List<TValue> getValue_list() {
    return this.value_list;
  }

  public TRangeValue setValue_list(List<TValue> value_list) {
    this.value_list = value_list;
    return this;
  }

  public void unsetValue_list() {
    this.value_list = null;
  }

  /** Returns true if field value_list is set (has been assigned a value) and false otherwise */
  public boolean isSetValue_list() {
    return this.value_list != null;
  }

  public void setValue_listIsSet(boolean value) {
    if (!value) {
      this.value_list = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case VALUE_LIST:
      if (value == null) {
        unsetValue_list();
      } else {
        setValue_list((List<TValue>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case VALUE_LIST:
      return getValue_list();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case VALUE_LIST:
      return isSetValue_list();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TRangeValue)
      return this.equals((TRangeValue)that);
    return false;
  }

  public boolean equals(TRangeValue that) {
    if (that == null)
      return false;

    boolean this_present_value_list = true && this.isSetValue_list();
    boolean that_present_value_list = true && that.isSetValue_list();
    if (this_present_value_list || that_present_value_list) {
      if (!(this_present_value_list && that_present_value_list))
        return false;
      if (!this.value_list.equals(that.value_list))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_value_list = true && (isSetValue_list());
    list.add(present_value_list);
    if (present_value_list)
      list.add(value_list);

    return list.hashCode();
  }

  @Override
  public int compareTo(TRangeValue other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetValue_list()).compareTo(other.isSetValue_list());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetValue_list()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.value_list, other.value_list);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TRangeValue(");
    boolean first = true;

    sb.append("value_list:");
    if (this.value_list == null) {
      sb.append("null");
    } else {
      sb.append(this.value_list);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (value_list == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'value_list' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TRangeValueStandardSchemeFactory implements SchemeFactory {
    public TRangeValueStandardScheme getScheme() {
      return new TRangeValueStandardScheme();
    }
  }

  private static class TRangeValueStandardScheme extends StandardScheme<TRangeValue> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TRangeValue struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // VALUE_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.value_list = new ArrayList<TValue>(_list8.size);
                TValue _elem9;
                for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                {
                  _elem9 = new TValue();
                  _elem9.read(iprot);
                  struct.value_list.add(_elem9);
                }
                iprot.readListEnd();
              }
              struct.setValue_listIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TRangeValue struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.value_list != null) {
        oprot.writeFieldBegin(VALUE_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.value_list.size()));
          for (TValue _iter11 : struct.value_list)
          {
            _iter11.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TRangeValueTupleSchemeFactory implements SchemeFactory {
    public TRangeValueTupleScheme getScheme() {
      return new TRangeValueTupleScheme();
    }
  }

  private static class TRangeValueTupleScheme extends TupleScheme<TRangeValue> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TRangeValue struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.value_list.size());
        for (TValue _iter12 : struct.value_list)
        {
          _iter12.write(oprot);
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TRangeValue struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.value_list = new ArrayList<TValue>(_list13.size);
        TValue _elem14;
        for (int _i15 = 0; _i15 < _list13.size; ++_i15)
        {
          _elem14 = new TValue();
          _elem14.read(iprot);
          struct.value_list.add(_elem14);
        }
      }
      struct.setValue_listIsSet(true);
    }
  }

}

