/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.baidu.palo.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2018-05-01")
public class TTopicItem implements org.apache.thrift.TBase<TTopicItem, TTopicItem._Fields>, java.io.Serializable, Cloneable, Comparable<TTopicItem> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TTopicItem");

  private static final org.apache.thrift.protocol.TField KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("key", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField INT_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("int_value", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField DOUBLE_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("double_value", org.apache.thrift.protocol.TType.DOUBLE, (short)3);
  private static final org.apache.thrift.protocol.TField STRING_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("string_value", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TTopicItemStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TTopicItemTupleSchemeFactory());
  }

  public String key; // required
  public long int_value; // optional
  public double double_value; // optional
  public String string_value; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    KEY((short)1, "key"),
    INT_VALUE((short)2, "int_value"),
    DOUBLE_VALUE((short)3, "double_value"),
    STRING_VALUE((short)4, "string_value");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // KEY
          return KEY;
        case 2: // INT_VALUE
          return INT_VALUE;
        case 3: // DOUBLE_VALUE
          return DOUBLE_VALUE;
        case 4: // STRING_VALUE
          return STRING_VALUE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __INT_VALUE_ISSET_ID = 0;
  private static final int __DOUBLE_VALUE_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.INT_VALUE,_Fields.DOUBLE_VALUE,_Fields.STRING_VALUE};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.KEY, new org.apache.thrift.meta_data.FieldMetaData("key", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.INT_VALUE, new org.apache.thrift.meta_data.FieldMetaData("int_value", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.DOUBLE_VALUE, new org.apache.thrift.meta_data.FieldMetaData("double_value", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.STRING_VALUE, new org.apache.thrift.meta_data.FieldMetaData("string_value", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TTopicItem.class, metaDataMap);
  }

  public TTopicItem() {
  }

  public TTopicItem(
    String key)
  {
    this();
    this.key = key;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TTopicItem(TTopicItem other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetKey()) {
      this.key = other.key;
    }
    this.int_value = other.int_value;
    this.double_value = other.double_value;
    if (other.isSetString_value()) {
      this.string_value = other.string_value;
    }
  }

  public TTopicItem deepCopy() {
    return new TTopicItem(this);
  }

  @Override
  public void clear() {
    this.key = null;
    setInt_valueIsSet(false);
    this.int_value = 0;
    setDouble_valueIsSet(false);
    this.double_value = 0.0;
    this.string_value = null;
  }

  public String getKey() {
    return this.key;
  }

  public TTopicItem setKey(String key) {
    this.key = key;
    return this;
  }

  public void unsetKey() {
    this.key = null;
  }

  /** Returns true if field key is set (has been assigned a value) and false otherwise */
  public boolean isSetKey() {
    return this.key != null;
  }

  public void setKeyIsSet(boolean value) {
    if (!value) {
      this.key = null;
    }
  }

  public long getInt_value() {
    return this.int_value;
  }

  public TTopicItem setInt_value(long int_value) {
    this.int_value = int_value;
    setInt_valueIsSet(true);
    return this;
  }

  public void unsetInt_value() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __INT_VALUE_ISSET_ID);
  }

  /** Returns true if field int_value is set (has been assigned a value) and false otherwise */
  public boolean isSetInt_value() {
    return EncodingUtils.testBit(__isset_bitfield, __INT_VALUE_ISSET_ID);
  }

  public void setInt_valueIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __INT_VALUE_ISSET_ID, value);
  }

  public double getDouble_value() {
    return this.double_value;
  }

  public TTopicItem setDouble_value(double double_value) {
    this.double_value = double_value;
    setDouble_valueIsSet(true);
    return this;
  }

  public void unsetDouble_value() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __DOUBLE_VALUE_ISSET_ID);
  }

  /** Returns true if field double_value is set (has been assigned a value) and false otherwise */
  public boolean isSetDouble_value() {
    return EncodingUtils.testBit(__isset_bitfield, __DOUBLE_VALUE_ISSET_ID);
  }

  public void setDouble_valueIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __DOUBLE_VALUE_ISSET_ID, value);
  }

  public String getString_value() {
    return this.string_value;
  }

  public TTopicItem setString_value(String string_value) {
    this.string_value = string_value;
    return this;
  }

  public void unsetString_value() {
    this.string_value = null;
  }

  /** Returns true if field string_value is set (has been assigned a value) and false otherwise */
  public boolean isSetString_value() {
    return this.string_value != null;
  }

  public void setString_valueIsSet(boolean value) {
    if (!value) {
      this.string_value = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case KEY:
      if (value == null) {
        unsetKey();
      } else {
        setKey((String)value);
      }
      break;

    case INT_VALUE:
      if (value == null) {
        unsetInt_value();
      } else {
        setInt_value((Long)value);
      }
      break;

    case DOUBLE_VALUE:
      if (value == null) {
        unsetDouble_value();
      } else {
        setDouble_value((Double)value);
      }
      break;

    case STRING_VALUE:
      if (value == null) {
        unsetString_value();
      } else {
        setString_value((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case KEY:
      return getKey();

    case INT_VALUE:
      return getInt_value();

    case DOUBLE_VALUE:
      return getDouble_value();

    case STRING_VALUE:
      return getString_value();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case KEY:
      return isSetKey();
    case INT_VALUE:
      return isSetInt_value();
    case DOUBLE_VALUE:
      return isSetDouble_value();
    case STRING_VALUE:
      return isSetString_value();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TTopicItem)
      return this.equals((TTopicItem)that);
    return false;
  }

  public boolean equals(TTopicItem that) {
    if (that == null)
      return false;

    boolean this_present_key = true && this.isSetKey();
    boolean that_present_key = true && that.isSetKey();
    if (this_present_key || that_present_key) {
      if (!(this_present_key && that_present_key))
        return false;
      if (!this.key.equals(that.key))
        return false;
    }

    boolean this_present_int_value = true && this.isSetInt_value();
    boolean that_present_int_value = true && that.isSetInt_value();
    if (this_present_int_value || that_present_int_value) {
      if (!(this_present_int_value && that_present_int_value))
        return false;
      if (this.int_value != that.int_value)
        return false;
    }

    boolean this_present_double_value = true && this.isSetDouble_value();
    boolean that_present_double_value = true && that.isSetDouble_value();
    if (this_present_double_value || that_present_double_value) {
      if (!(this_present_double_value && that_present_double_value))
        return false;
      if (this.double_value != that.double_value)
        return false;
    }

    boolean this_present_string_value = true && this.isSetString_value();
    boolean that_present_string_value = true && that.isSetString_value();
    if (this_present_string_value || that_present_string_value) {
      if (!(this_present_string_value && that_present_string_value))
        return false;
      if (!this.string_value.equals(that.string_value))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_key = true && (isSetKey());
    list.add(present_key);
    if (present_key)
      list.add(key);

    boolean present_int_value = true && (isSetInt_value());
    list.add(present_int_value);
    if (present_int_value)
      list.add(int_value);

    boolean present_double_value = true && (isSetDouble_value());
    list.add(present_double_value);
    if (present_double_value)
      list.add(double_value);

    boolean present_string_value = true && (isSetString_value());
    list.add(present_string_value);
    if (present_string_value)
      list.add(string_value);

    return list.hashCode();
  }

  @Override
  public int compareTo(TTopicItem other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetKey()).compareTo(other.isSetKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.key, other.key);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetInt_value()).compareTo(other.isSetInt_value());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInt_value()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.int_value, other.int_value);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDouble_value()).compareTo(other.isSetDouble_value());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDouble_value()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.double_value, other.double_value);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetString_value()).compareTo(other.isSetString_value());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetString_value()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.string_value, other.string_value);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TTopicItem(");
    boolean first = true;

    sb.append("key:");
    if (this.key == null) {
      sb.append("null");
    } else {
      sb.append(this.key);
    }
    first = false;
    if (isSetInt_value()) {
      if (!first) sb.append(", ");
      sb.append("int_value:");
      sb.append(this.int_value);
      first = false;
    }
    if (isSetDouble_value()) {
      if (!first) sb.append(", ");
      sb.append("double_value:");
      sb.append(this.double_value);
      first = false;
    }
    if (isSetString_value()) {
      if (!first) sb.append(", ");
      sb.append("string_value:");
      if (this.string_value == null) {
        sb.append("null");
      } else {
        sb.append(this.string_value);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (key == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'key' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TTopicItemStandardSchemeFactory implements SchemeFactory {
    public TTopicItemStandardScheme getScheme() {
      return new TTopicItemStandardScheme();
    }
  }

  private static class TTopicItemStandardScheme extends StandardScheme<TTopicItem> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TTopicItem struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.key = iprot.readString();
              struct.setKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // INT_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.int_value = iprot.readI64();
              struct.setInt_valueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DOUBLE_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.double_value = iprot.readDouble();
              struct.setDouble_valueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // STRING_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.string_value = iprot.readString();
              struct.setString_valueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TTopicItem struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.key != null) {
        oprot.writeFieldBegin(KEY_FIELD_DESC);
        oprot.writeString(struct.key);
        oprot.writeFieldEnd();
      }
      if (struct.isSetInt_value()) {
        oprot.writeFieldBegin(INT_VALUE_FIELD_DESC);
        oprot.writeI64(struct.int_value);
        oprot.writeFieldEnd();
      }
      if (struct.isSetDouble_value()) {
        oprot.writeFieldBegin(DOUBLE_VALUE_FIELD_DESC);
        oprot.writeDouble(struct.double_value);
        oprot.writeFieldEnd();
      }
      if (struct.string_value != null) {
        if (struct.isSetString_value()) {
          oprot.writeFieldBegin(STRING_VALUE_FIELD_DESC);
          oprot.writeString(struct.string_value);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TTopicItemTupleSchemeFactory implements SchemeFactory {
    public TTopicItemTupleScheme getScheme() {
      return new TTopicItemTupleScheme();
    }
  }

  private static class TTopicItemTupleScheme extends TupleScheme<TTopicItem> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TTopicItem struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.key);
      BitSet optionals = new BitSet();
      if (struct.isSetInt_value()) {
        optionals.set(0);
      }
      if (struct.isSetDouble_value()) {
        optionals.set(1);
      }
      if (struct.isSetString_value()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetInt_value()) {
        oprot.writeI64(struct.int_value);
      }
      if (struct.isSetDouble_value()) {
        oprot.writeDouble(struct.double_value);
      }
      if (struct.isSetString_value()) {
        oprot.writeString(struct.string_value);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TTopicItem struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.key = iprot.readString();
      struct.setKeyIsSet(true);
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.int_value = iprot.readI64();
        struct.setInt_valueIsSet(true);
      }
      if (incoming.get(1)) {
        struct.double_value = iprot.readDouble();
        struct.setDouble_valueIsSet(true);
      }
      if (incoming.get(2)) {
        struct.string_value = iprot.readString();
        struct.setString_valueIsSet(true);
      }
    }
  }

}

